name: Discord Webhook
on: push
jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub",
            "embeds": [{
              "title": "New Push Event",
              "description": "A new push event happened in the repo.",
              "color": 65280
            }]
          }' ${{ secrets.DISCORD_WEBHOOK }}
